# Generated by Django 4.1.3 on 2022-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='anonymous.png', upload_to='profile_pics'),
        ),
    ]
